### ISSUE TITLE
Epic: 1 Story: 3 Complete information on BullHacks page

### ISSUE THREAD

**Issue by luketainton** [HaCSBCU/hacsbcu.github.io#116]
### Description
bullhacks.html needs more information on it, ready for when the committee decide to start marketing for BullHacks 3.0.

### To Do
Add more information to the body of the page.

### Checklist

- [ ] Complete 'What is BullHacks?' section.

- [ ] Complete 'Sponsors' section.

- [ ] Add additional sections as required.
