### ISSUE TITLE
Epic: 1 Story: 5 Complete information on Committee page

### ISSUE THREAD

**Issue by luketainton** [HaCSBCU/hacsbcu.github.io#118]
### Description
The committee page explains what the committee does for the society, and also provides an insight into the current committee members. 

### To Do
Add information about the purpose of the committee and who they are.

### Checklist

- [ ] Add Committee group photo as page banner.

- [ ] Complete 'Who are we?' section.

- [ ] Complete sections about each member.

**Comment by luketainton** [comment]
@HalcyonHawk if you don't mind, could you add some information about yourself? Just a quick couple of lines about why you ran for VP, what you'd like to do etc.

Thanks!
